name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env: 
      PROJECT: "src/Onbox.TypeSharp/Onbox.TypeSharp.csproj"
    steps:
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Build
      run: dotnet build $PROJECT
