name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Restore dependencies
      run: dotnet restore "actions/checkout/src/Onbox.TypeSharp/Onbox.TypeSharp.csproj"
    - name: Build
      run: dotnet build "actions/checkout/src/Onbox.TypeSharp/Onbox.TypeSharp.csproj"
