name: .NET
env: 
  Project: "src/Onbox.TypeSharp/Onbox.TypeSharp.csproj"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Restore dependencies
      run: dotnet restore ${Project}
    - name: Build
      run: dotnet build ${Project}
